---
- name: "Check if installer file exists"
  ansible.builtin.stat:
    path: "files/{{ installer[ansible_facts['os_family'] | lower] }}"
  delegate_to: localhost
  become: false
  register: install_file

- name: "Installer File not found"
  ansible.builtin.fail:
    msg: "No installation file for the installation on {{ ansible_facts['os_family'] }} {{ ansible_architecture }} found. Please check if the file is defined and saved in the files/ directory."
  when: not install_file.stat.exists

- name: "Start tasks for each distribution"
  when:
    - ansible_facts['os_family'] | lower in available_installers
    - install_file.stat.exists
  block:
    - name: "Run install script for distribution"
      ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] | lower }}_{{ ansible_architecture | lower }}.yml"

    - name: "Run post install tasks"
      ansible.builtin.include_tasks: "post_installation.yml"
