---
- name: "Copy install package to server"
  ansible.builtin.copy:
    src: files/{{ installer }}
    dest: /tmp/{{ installer }}
    mode: "0600"

- name: "Install package"
  ansible.builtin.apt:
    deb: /tmp/{{ installer }}
    state: present
  become: true

- name: "Add user to the 'adm' group for reading the /var/log/ directory"
  ansible.builtin.user:
    name: humio-log-collector
    groups: adm
    append: yes
  notify: Restart humio-log-collector service
