---
- name: "REDHAT - Copy install package to server"
  ansible.builtin.copy:
    src: files/{{ installer.redhat }}
    dest: /tmp/{{ installer.redhat }}
    mode: "0600"

- name: "REDHAT - Install package"
  ansible.builtin.yum:
    name: /tmp/{{ installer.redhat }}
    disable_gpg_check: true
    state: present
  become: true
